### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cedricve** [RSATom/ya-libvlc-wrapper#2]
Looks good.. however a more detailed readme should be nice :)

**Comment by RSATom** [comment]
This library is not intended for wide public use. It's only helper lib for my other projects. On other side, this lib is just very tiny wrapper about libvlc API, so it's pretty easy to understand it if you familiar with original libvlc API

**Comment by cedricve** [comment]
Ok, I understand :) However a little more detail would be helpful.  Thank you for the fast answer.

**Comment by RSATom** [comment]
just look to headers - it has very simple logic.

first of all this lib intended to avoid check if libvlc was opened previously (or some other handles), before every call of some libvlc function.

**Comment by RSATom** [comment]
if you need something more functional you could look to official wrapper from videolan team: https://code.videolan.org/videolan/libvlcpp But don't sure how well it's documented

**Comment by cedricve** [comment]
Thank you for the help Sergey, I would like to use your API to fetch a RTSP stream and send it to a file.
E.g. VLC -vvv rtsp://192.168.0.135/axis-media/media.amp --sout=file/ps:go-axis.mpg

But than with your library.

**Comment by RSATom** [comment]
So you need create some UI with ability play video, right? what UI framework you plan to use?

**Comment by cedricve** [comment]
Not really, it should be a basic command line application for the moment. Which just opens the stream and write it to a file. No UI for this moment.

**Comment by RSATom** [comment]
ah... understand.. then maybe you even don't need any wrapper. libvlc api is pretty high level.

**Comment by RSATom** [comment]
I'll look, maybe I've did some basic example...

**Comment by cedricve** [comment]
Hmm, thanks for the help. That would be great.

**Comment by RSATom** [comment]
Something like this:

```
#include "vlc_player.h"

int main(int argc, char* argv[])
{
    char* libvlc_arg[] = {
        "-vv",
        "--sout=file/ps:go-axis.mpg"
    };

    libvlc_instance_t* libvlc = libvlc_new( sizeof(libvlc_arg) / sizeof(libvlc_arg[0]), libvlc_arg );

    vlc::player player;
    player.open(libvlc);

    player.add_media("rtsp://192.168.0.135/axis-media/media.amp");
    player.play();

    for(auto state = player.get_state(); state != libvlc_Ended && state != libvlc_Error; state = player.get_state())
        Sleep(1000);

    return 0;
}
```

**Comment by RSATom** [comment]
but I didn't run it, it could contain some errors.

**Comment by cedricve** [comment]
Great! looks perfect what I need. Just having a linker error with the VLC library: 

Undefined symbols for architecture x86_64:
  "_libvlc_new", referenced from:

Any idea which library I also need to include? I already included the liblibvlc_wrapper.a
I'm on OSX.

Thanks for your help 👍

**Comment by RSATom** [comment]
~~you need link it with `lib/msvc/libvlc.lib` from https://github.com/RSATom/libvlc-sdk~~

**Comment by RSATom** [comment]
ah... OSX... wait a minute

**Comment by RSATom** [comment]
you should `-L/Applications/VLC.app/Contents/MacOS/lib -lvlc`

**Comment by RSATom** [comment]
but to run it, you should use slightly modified version of vlc. You could take one from https://github.com/RSATom/WebChimera.js/releases/download/v0.2.6/WebChimera.js_v0.2.6_electron_v0.37.6_VLC_v2.2.4_x64_osx.tar.gz

https://github.com/RSATom/WebChimera.js/wiki/Due-to-bug-libvlc-2.2.x-could-not-be-used-as-is-outside-VLC.app-on-Mac-OS-X

**Comment by RSATom** [comment]
of course instead of `-L/Applications/VLC.app/Contents/MacOS/lib` you could use path to `libvlc.dylib` from above archive

**Comment by cedricve** [comment]
Awesome help Sergey, very appreciated. I've copied the library from your webchimera project and it links correctly. I assume there is no static library available?

![screen shot 2016-08-19 at 15 33 13](https://cloud.githubusercontent.com/assets/1546779/17811318/641fbb82-6622-11e6-87a0-375bb13e9b89.png)

**Comment by RSATom** [comment]
libvlc could be built statically but usually it used only for mobile platforms (Android/iOs). I've never did it for desktop.

**Comment by RSATom** [comment]
So, did you get your `file/ps:go-axis.mpg`?

I'm still don't sure if it will work...

**Comment by cedricve** [comment]
It works! Thank you for all your help! For what is the get_state? What is to most proper solution to stop the recording and finish it?

```
    char* libvlc_arg[] = {
        "-vv",
        "--sout=file/ps:go-axis.mpg"
    };

    libvlc_instance_t* libvlc = libvlc_new( sizeof(libvlc_arg) / sizeof(libvlc_arg[0]), libvlc_arg );

    vlc::player player;
    player.open(libvlc);

    player.add_media("rtsp://192.168.0.135/axis-media/media.amp");
    player.play();

    for(auto state = player.get_state(); state != libvlc_Ended && state != libvlc_Error; state = player.get_state())
    usleep(1000000);
```

![screen shot 2016-08-19 at 15 44 04](https://cloud.githubusercontent.com/assets/1546779/17811649/f2bceb02-6623-11e6-9d58-c904538324d6.png)

**Comment by RSATom** [comment]
:+1: 

> For what is the get_state?

it just returns current playback state: https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#gac88ad60037ea05e1f23675a2ebe31efc

> What is to most proper solution to stop the recording and finish it?

I think it will be enough just do `player.stop()`

**Comment by cedricve** [comment]
Do you know if it's also possible to capture a USB device E.g. a webcam.
Currently looking at the media API, but don't find something similar.

**Comment by RSATom** [comment]
unfortunately can't find something useful too

**Comment by cedricve** [comment]
For OSX this works, I assume that this will be /dev/video0 for linux. However when I add it to player.add_media that doesn't work.

`/Applications/VLC.app/Contents/MacOS/VLC  -vvv qtcapture://`

When running the player.play() command it hangs.

**Comment by RSATom** [comment]
I have an idea, try run it with

`player.add_media("qtcapture://", false);`

it will open it as local file then
